version: '3.1'
services:
  oracledb:
    image: container-registry.oracle.com/database/express:21.3.0-xe
    restart: unless-stopped
    ports:
      - 1521:1521
      - 5500:5500
    environment:
      ORACLE_PWD: password#1
      ORACLE_EDITION: express
